# The number of seconds until an rtp request automatically times out
request-timeout: 120
# Enable permissions
permissions: true
# Maximum requests a player can receive
request-max: 10
# Require player names to be exact (not case sensitive)
require-full-name: true