name: TeleportRequest
main: me.cnaude.plugin.TeleportRequest.TR
version: 0.3.0
description: Send teleport reuqests to other players!
author: Chris Naude
commands:
    rtp:
        description: Send a teleport request to another player.
        usage: |
               /<command> [player|yes|no] ([player|all])
               /rtp [player] - Send a teleport request to [player]. 
               /rtp [yes|no] ([player|all]) - Accept or deny teleport request from another player(s).
permissions: 
    teleportrequest.rtp:
        description: Gives player access to /rtp.
        default: false 
    rtp.use:
        description: Gives player access to /rtp.
        default: false 
    teleportrequest.admin:
        description: Allows players to send rtp requests without the need for approval from the destination player.
        default: false 
    rtp.admin:
        description: Allows players to send rtp requests without the need for approval from the destination player.
        default: false         